autoload :Application,     'lib/application'
autoload :Archtecture,     'lib/archtecture'
autoload :Config,          'lib/config'
autoload :Container,       'lib/container'
autoload :ComposerBuilder, 'lib/composer_builder'
autoload :Setup,           'lib/setup'
